package wordleandnerdle;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static wordleandnerdle.Gameover.caseforpanel;
import wordleandnerdle.Registersystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mac
 */
public class Goodgame extends javax.swing.JFrame {

    /**
     * Creates new form Goodgame
     */
    
    public Goodgame() {
        initComponents();
        setTitle("GOOD GAME");
        Toolkit obj=getToolkit();
        Dimension size=obj.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight());
        String name=Registersystem.getUsername();
        lblscore.setText(String.format("%s, YOU GET %d POINTS!",name,0));
        lbltotalscore.setText(String.format("YOU HAVE %d POINTS",0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpnl = new javax.swing.JPanel();
        lblExcellent = new javax.swing.JLabel();
        lblscore = new javax.swing.JLabel();
        lbltotalscore = new javax.swing.JLabel();
        btnBacktomenu = new javax.swing.JButton();
        btnPlayagain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainpnl.setBackground(new java.awt.Color(0, 153, 255));

        lblExcellent.setFont(new java.awt.Font("Baskerville", 3, 48)); // NOI18N
        lblExcellent.setForeground(new java.awt.Color(255, 255, 255));
        lblExcellent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExcellent.setText("Excellent!");

        lblscore.setForeground(new java.awt.Color(255, 255, 255));

        lbltotalscore.setForeground(new java.awt.Color(255, 255, 255));

        btnBacktomenu.setBackground(new java.awt.Color(0, 153, 255));
        btnBacktomenu.setForeground(new java.awt.Color(255, 255, 255));
        btnBacktomenu.setText("BACK TO MENU");
        btnBacktomenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBacktomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktomenuActionPerformed(evt);
            }
        });

        btnPlayagain.setBackground(new java.awt.Color(0, 153, 255));
        btnPlayagain.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayagain.setText("PLAY AGAIN");
        btnPlayagain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlayagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayagainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpnlLayout = new javax.swing.GroupLayout(mainpnl);
        mainpnl.setLayout(mainpnlLayout);
        mainpnlLayout.setHorizontalGroup(
            mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPlayagain, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBacktomenu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(mainpnlLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(lbltotalscore, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpnlLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpnlLayout.createSequentialGroup()
                        .addComponent(lblscore, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpnlLayout.createSequentialGroup()
                        .addComponent(lblExcellent, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
        );
        mainpnlLayout.setVerticalGroup(
            mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpnlLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblExcellent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblscore, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltotalscore, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPlayagain, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnBacktomenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayagainActionPerformed
        // TODO add your handling code here:
        if(caseforpanel.length()>5){
            dispose();
            new Nerdle().setVisible(true);
        }
        else{
            dispose();
            try {
                new Wordle().setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Gameover.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnPlayagainActionPerformed

    private void btnBacktomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktomenuActionPerformed
        // TODO add your handling code here:
        dispose();
        new ENTRYPAGE().setVisible(true);
    }//GEN-LAST:event_btnBacktomenuActionPerformed

    /**
     * @param args the command line arguments
     */
    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBacktomenu;
    private javax.swing.JButton btnPlayagain;
    private javax.swing.JLabel lblExcellent;
    private javax.swing.JLabel lblscore;
    private javax.swing.JLabel lbltotalscore;
    private javax.swing.JPanel mainpnl;
    // End of variables declaration//GEN-END:variables
}
